config/routes.rb
Posterchild::Application.routes.draw do
  devise_for :users
  resources :tags
  get "settings" => "settings#index"
  get "explore" => "explore#index"

root 'posts#index'

resources :posts do
end

post "posts/feedhook/:id" => "posts#feedhook"

resources :feeds do
  collection do
    get :bulk_form
    get :healthcheck
  end
end

post "feeds/bulk_form" => "feeds#bulk_form"

get "feeds/healthcheck" => "feeds#healthcheck"

resources :pages do
  collection do
    get "pages/page" => "pages#show"
  end
end

resources :donations

end

app/models/feed.rb
class Feed
  include Mongoid::Document
  include Mongoid::Alize

  field :title, type: String
  field :url, type: String
  field :tags, type: Array

  has_many :posts 

  def tag_list
    if ( self.tags.kind_of?(Array) )
      self.tags.map { |t| t }.join(", ")
    else
      ""
    end
  end


end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  require 'csv'
  require 'uri'


  # REQUIRE LOGGED USER!

  # GET /feeds
  def index
    @feeds = Feed.all
  end


  def healthcheck
    @feeds = Post.collection.aggregate([
    { "$sort" => { "feed_fields.title" => 1, "published" => 1 } },
    { "$group" => {
      "_id"       => "$feed_fields.title",
      "lastDate"  => { "$last" => "$published" },
      "postTitle"     => { "$last": "$title"},
      "postPermalinkUrl"     => { "$last": "$permalinkUrl"}
    }},
    { "$sort" => { "lastDate" => -1 } }
    ])
  end

  def bulk_form
    #insert/update feeds from json in localhost:3000/feeds/bulk_form

    if params[:feeds].present?

      if valid_json?( params[:feeds])
        #iterate json array
        JSON.parse(params[:feeds]).each do |item|

          #create feed
          t_feed = Feed.new({:title=>item['Title'], :url=>item['Url'], :tags => item['Tags'].split(',') })

          #check if feed exists in db
          feed = Feed.where(title: item["Title"]).first

          logger.info "#{feed.inspect}"
          #update if there are changes
          if feed
            Rails.logger.info "IN DB"
            if is_update_needed(feed, t_feed)
              feed.update(title: t_feed.title, url: t_feed.url,tags: t_feed.tags)
              Rails.logger.info "UPDATED"
            end
          else
            Rails.logger.info "CREATED"
            #subscribe to superfeedr & save in db and save posts
            subscribe ( t_feed )
          end

        end

        @params ="OK"
      end
    end

    #respond_to do |format|
    #  format.html { redirect_to feeds_url, notice: 'CSV Feeds were successfully updated.' }
    #end
  end



  # GET /feeds/1
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  def create

    params[:feed][:tags] = params[:feed][:tag_list].split(',')
    params[:feed][:tags] = params[:feed][:tags].collect{|x| x.strip}
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /feeds/1
  def update

    params[:feed][:tags] = params[:feed][:tag_list].split(',')
    params[:feed][:tags] = params[:feed][:tags].collect{|x| x.strip}

    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /feeds/1
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:title, :url, :id, :tags => [])
    end

  def valid_json?(json)
    begin
      JSON.parse(json)
      return true
    rescue Exception => e
      return false
    end
  end

  def is_update_needed (feed, t_feed)
    if (
      feed.title != t_feed.title ||
      feed.url != t_feed.url ||
      feed.tags != t_feed.tags
      )
      return true
    end
    return false
  end
  
  def get_tags (item)
    #create tags array
    tags = []
    notags=["Title", "Website", "Url"]
    item.each do |property, value|
      if notags.exclude? property and value == 1
        tags.push (property)
      end
    end
    return tags
  end

  def subscribe ( t_feed )

    @result = "result"
    # Configure the middleware with Environment vars in .rben-vars
    Rack::Superfeedr.host = ENV['SUPERFEEDER_HOST']
    Rack::Superfeedr.login = 'earlyriser'
    Rack::Superfeedr.password = 'supermancit0**'
    Rack::Superfeedr.base_path = '/posts/feedhook/'+Rails.configuration.site[:id]+'_'


    Rack::Superfeedr.subscribe(t_feed.url, t_feed.id, {format: "json", secret:ENV['SUPERFEEDER_SECRET'], retrieve: true }) do |body, success, response|

      if success
        flash[:notice] = "Pub/sub OK"
        temp = JSON.parse(body, :quirks_mode => true)
        code_initial = temp["status"]["code"].to_s[0,1]
        @result = body
        logger.info  temp["status"]
        logger.info code_initial

        #if subscribe is ok,
        if ( code_initial =='2' || code_initial =='3' )

          #insert feed in db
          t_feed.save

          #then insert last retrieved posts in db
          temp["items"].each do |item|
            post_j = {
              :title => item["title"],
              :published => item["published"],
              :permalinkUrl => item["permalinkUrl"]
            }
            @post = Post.new(post_j)
            @post.feed = t_feed
            @post.save

          end
        end
      else
        flash[:notice] = "Pub/sub ERROR"
        temp = JSON.parse(body, :quirks_mode => true)
        @result = body
        logger.info  @result
      end
    end
  end



end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>

  <%= @feed.tags %>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/bulk_form.html.erb
<h1>BULK FORM</h1>
<p>Enter your json string</p>

 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%= form_tag("/feeds/bulk_form", method: "post")  do %>
  <%= text_area_tag "feeds"  %>
  <%= submit_tag "Save" %>
<% end %>

<%= link_to 'Back', feeds_path %>

<%= @params.inspect %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/healthcheck.html.erb
<h1>HEALTHCHECK</h1>
<p>Latest post of every feed</p>

<div class="adminView">
  <table>
    <% @feeds.each do |feed| %>
      <tr>
        <td style="line-height:1.4em;">
          <a href="<%= posts_path(:by => feed["_id"]) %>" >
            &nbsp;<%=feed["_id"] %>
          </a>
        </td>
        <td><%= feed["lastDate"] %></td>
        <td><%= Time.zone.at( feed["lastDate"].to_i ).strftime("%B %d, %Y") %> </td>
        <td>
          <a href="<%=feed["postPermalinkUrl"] %>" >
            <%= feed["postTitle"] %>
          </a>
        </td>
      </tr>
      <% end %>
  </table>
</div>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Id</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.url %></td>
        <td><%= feed.id %></td>
        <td><%= feed.tags %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Bulk insert', bulk_form_feeds_path  %>
<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Id:</strong>
  <%= @feed.id %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @feed.tags %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>