config/routes.rb
Posterchild::Application.routes.draw do
  devise_for :users
  resources :tags
  get "settings" => "settings#index"
  get "explore" => "explore#index"

root 'posts#index'

resources :posts do
end

post "posts/feedhook/:id" => "posts#feedhook"

resources :feeds do
  collection do
    get :bulk_form
    get :healthcheck
  end
end

post "feeds/bulk_form" => "feeds#bulk_form"

get "feeds/healthcheck" => "feeds#healthcheck"

resources :pages do
  collection do
    get "pages/page" => "pages#show"
  end
end

resources :donations

end

app/views/shared/_footer.html.erb
  <div id="footer">
    <ul>
      <li><a href="https://medium.com/@techtronium/techtronium-startup-news-in-a-simpler-format-703483d628d1#.ryy2ydld4">About</a></li>
      <li><a href="<%=explore_path() %>"><span class="fa fa-rocket"></span> Explore</a></li>
      <li><a href="http://medium.com/@techtronium">Blog</a></li>
      <li><a href="<%=page_path('tos' ) %>">Terms</a></li>
      <li><a href="<%=page_path('privacy' ) %>">Privacy</a></li>
    </ul>
  </div>

app/views/shared/_header.html.erb
<div id="header">
    <div id="brand">
      <a href="<%=posts_path()%>">
        <%= image_tag("logo.svg", :id => "logo") %>
        <%= image_tag("wordmark.svg", :id => "wordmark") %>
        <span id="tagline"><%= Rails.configuration.site[:tagline] %></span>
        <span id="shorttagline"><%= Rails.configuration.site[:shorttagline] %></span>
      </a>

    </div>

    <div id="tools">
        <span class="tool" id="highlightOrb">
            <a href="javascript:void(0)">
              <span id="highlightedCounter"></span>
              <i id="highlightPulse" class="fa fa-star-o"></i>
              <i class="fa fa-star fa-lg" style="line-height: 1.4em;"></i>
            </a>
        </span>
        <span class="tool <%= 'selected' if current_page?(settings_path)  %>">
          <a href="<%=settings_path()%>">

            <i class="fa fa-gear fa-lg" style="line-height: 1.4em;"></i>
          </a>
        </span>
    </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
    <div id="sidebarContent">
        Fresh news from hundreds of web companies<br><br>
        No votes.<br><br>
        No gossip.<br><br>
        No comments.<br><br>
        No speculation.<br><br><br><br><br><br>

        <div id="tagsSidebar" class="group">
          Tags:
            <span><%=link_to "All", posts_path %></span>
            <% Rails.configuration.site[:tags].each do |tag| %>
                <span ><%=link_to tag, posts_path(:tag => tag) %></span>
            <% end %>
        </div>
        
        <!-- 
        <div class="meter">
          <a href="<%=new_donation_path()%>"><span style="width: 38%"></span></a>
        </div>
          
        <div class="donationBar"><span class="donationLevel"></span></div>
        <p style="text-align:center;">
          <a href="<%=new_donation_path()%>" style="text-decoration:underline;">
            Donate to keep us running. <br><br>
            We need $100/month.
          </a>
        </p> -->
        
    </div>
</div>