config/routes.rb
Posterchild::Application.routes.draw do
  devise_for :users
  resources :tags
  get "settings" => "settings#index"
  get "explore" => "explore#index"

root 'posts#index'

resources :posts do
end

post "posts/feedhook/:id" => "posts#feedhook"

resources :feeds do
  collection do
    get :bulk_form
    get :healthcheck
  end
end

post "feeds/bulk_form" => "feeds#bulk_form"

get "feeds/healthcheck" => "feeds#healthcheck"

resources :pages do
  collection do
    get "pages/page" => "pages#show"
  end
end

resources :donations

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def new
    render layout: "application"
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    donation = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => params[:amount],
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_donation_path
  end
  
end

app/views/donations/create.html.erb
<div id="main" class="group">
    <div id="content">

      <%= render "shared/header" %>

      
      <h1>Thanks for your donation!</h1><br>

      <div class="page">
          
      </div>

      <%= render "shared/footer" %>

  </div>

  <%= render "shared/sidebar" %>

</div>

app/views/donations/new.html.erb
<div id="main" class="group">
    <div id="content">

      <%= render "shared/header" %>

      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
      </article>
      
      <h1>We need your help</h1><br>

        <div class="page">
          <p>
            Techtronium is an experiment, not a company.<br>
            Running it requires more money than the average side project.<br>
            
            If you love Techtronium, please donate and you'll:
            <ul>
              <li>- Keep us online.</li>
              <li>- Increase the companies we track.</li>
              <li>- Receive a Techtronium sticker (StickerMule quality) with a $50 and up donation.</li> 
            </ul>
            
            <br>
            A small $5 donation will keep it running for one and a half days.
          </p>
          
          <p>
            Main costs: Hosting (DigitalOcean) and feed API (Superfeedr).
          </p>
 
 <script src="https://checkout.stripe.com/checkout.js" ></script>
 
          <%= form_tag donations_path do %>
            <input type="hidden" name="amount" value="">
            <input type="hidden" name="stripeToken" value="">
            <input type="hidden" name="stripeEmail" value="">
          <% end %>
          
          <button class="button short" id="custom5">Donate $5</button>
          <button class="button short" id="custom10">Donate $10</button>
          <button class="button short" id="custom20">Donate $20</button>
          <button class="button short" id="custom50">Donate $50</button>
          <button class="button short" id="custom100">Donate $100</button>

          <script>
            var handler = StripeCheckout.configure({
              key: 'pk_wm8iC1EI3cxqBzoG4jwkBTgObnLhE',
              image: '<%= asset_path "logo.svg" %>',
              locale: 'auto',
              name: 'Techtronium',
              token: function(token) {
                $( "input[name='stripeToken']" ).val(token.id);
                $( "input[name='stripeEmail']" ).val(token.email);
                $("form").submit();                
              }
            });
            
            var clickBtn = function(e, dollars){
              var amount = dollars*100
              $( "input[name='amount']" ).val(amount);
              handler.open({
                description: dollars+' bucks donation, cool!',
                amount: amount
              });
              e.preventDefault();
                          
            }

            $('#custom5').on('click', function(e) {
              clickBtn ( e, 5)
            });
                    
            $('#custom10').on('click', function(e) {
              clickBtn ( e, 10)
            });
            
            $('#custom20').on('click', function(e) {
              clickBtn ( e, 20)
            });
            
            $('#custom50').on('click', function(e) {
              clickBtn ( e, 50)
            });  
            
            $('#custom100').on('click', function(e) {
              clickBtn ( e, 100)
            });                                                

            // Close Checkout on page navigation:
            $(window).on('popstate', function() {
              handler.close();
            });
          </script>
                  

      </div>

      <%= render "shared/footer" %>

  </div>

  <%= render "shared/sidebar" %>

</div>

<script type="text/javascript">
    mixpanel.track("donations visit", {});    
</script>